In [1]:
import os
import pandas as pd

In [2]:
DATA_DIR = './data'

In [3]:
agency_df = pd.read_csv(os.path.join(DATA_DIR, 'AgencyMaster.csv'))
employee_df = pd.read_csv(os.path.join(DATA_DIR, 'EmpMaster.csv'))
title_df = pd.read_csv(os.path.join(DATA_DIR, 'TitleMaster.csv'))
payroll2021_df = pd.read_csv(os.path.join(DATA_DIR, 'nycpayroll_2021.csv'))
payroll2020_df = pd.read_csv(os.path.join(DATA_DIR, 'nycpayroll_2020.csv'))

In [4]:
agency_df.head()

   AgencyID                      AgencyName
0      2001       ADMIN FOR CHILDREN'S SVCS
1      2002       ADMIN TRIALS AND HEARINGS
2      2003             BOARD OF CORRECTION
3      2004               BOARD OF ELECTION
4      2005  BOARD OF ELECTION POLL WORKERS

In [5]:
employee_df.head()

   EmployeeID LastName FirstName
0      100001   AACHEN     DAVID
1      100002   AACHEN    MONICA
2      100003   AADAMS   LAMMELL
3      100004    AADIL      IRIS
4      100005   AALAAM      AMIR

In [6]:
title_df.head()

   TitleCode                TitleDescription
0      40001  *ADM SCHOOL SECURITY MANAGER-U
1      40002       *ADMIN SCHL SECUR MGR-MGL
2      40003                *AGENCY ATTORNEY
3      40004          *ASSISTANT ADVOCATE-PD
4      40005    *ASSOCIATE EDUCATION OFFICER

In [7]:
payroll2020_df.head()

,FiscalYear,PayrollNumber,AgencyID,AgencyName,EmployeeID,LastName,FirstName,AgencyStartDate,WorkLocationBorough,TitleCode,TitleDescription,LeaveStatusasofJune30,BaseSalary,PayBasis,RegularHours,RegularGrossPaid,OTHours,TotalOTPaid,TotalOtherPay
0,2020,17,2120,OFFICE OF EMERGENCY MANAGEMENT,10001,GEAGER,VERONICA,9/12/2016,BROOKLYN,40447,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,84698.21,0.0,0.0,0.00
1,2020,17,2120,OFFICE OF EMERGENCY MANAGEMENT,149612,ROTTA,JONATHAN,9/16/2013,BROOKLYN,40447,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,84698.21,0.0,0.0,0.00
2,2020,17,2120,OFFICE OF EMERGENCY MANAGEMENT,206583,WILSON II,ROBERT,4/30/2018,BROOKLYN,40447,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,84698.21,0.0,0.0,0.00
3,2020,17,2120,OFFICE OF EMERGENCY MANAGEMENT,199874,WASHINGTON,MORIAH,3/18/2019,BROOKLYN,40447,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,87900.95,0.0,0.0,-3202.74
4,2020,17,2120,OFFICE OF EMERGENCY MANAGEMENT,58036,KRAWCZYK,AMANDA,5/15/2017,BROOKLYN,40447,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,83976.54,0.0,0.0,0.00

In [8]:
payroll2021_df.head()

,FiscalYear,PayrollNumber,AgencyCode,AgencyName,EmployeeID,LastName,FirstName,AgencyStartDate,WorkLocationBorough,TitleCode,TitleDescription,LeaveStatusasofJune30,BaseSalary,PayBasis,RegularHours,RegularGrossPaid,OTHours,TotalOTPaid,TotalOtherPay
0,2021,996,2153,NYC HOUSING AUTHORITY,209184,MUSTACIUOLO,VITO,2/26/2018,MANHATTAN,40475,EXECUTIVE DIRECTOR,ACTIVE,258000.0,per Annum,1820,257260.30,0.00,0.00,258000.00
1,2021,996,2153,NYC HOUSING AUTHORITY,302330,RUSS,GREGORY,8/12/2019,MANHATTAN,41143,CHAIR,ACTIVE,414707.0,per Annum,1820,413518.05,0.00,0.00,500.00
2,2021,816,2129,DEPT OF HEALTH/MENTAL HYGIENE,49788,HALLAHAN,PATRICK,2/26/2018,BROOKLYN,40782,STATIONARY ENGINEER,ACTIVE,508.8,per Day,2080,132288.00,2115.25,218628.18,56616.07
3,2021,816,2129,DEPT OF HEALTH/MENTAL HYGIENE,251626,PETTIT,PATRICK,8/2/2010,MANHATTAN,40782,STATIONARY ENGINEER,ACTIVE,508.8,per Day,2080,132288.00,2152.75,218694.96,38611.82
4,2021,816,2129,DEPT OF HEALTH/MENTAL HYGIENE,364376,TELEHANY,STEPHEN,1/16/2007,QUEENS,40782,STATIONARY ENGINEER,ACTIVE,508.8,per Day,2080,132288.00,1876.25,192296.19,51160.20

In [9]:
payroll2021_df.value_counts()

FiscalYear  PayrollNumber  AgencyCode  AgencyName                     EmployeeID  LastName   FirstName  AgencyStartDate  WorkLocationBorough  TitleCode  TitleDescription                              LeaveStatusasofJune30  BaseSalary  PayBasis   RegularHours  RegularGrossPaid  OTHours  TotalOTPaid  TotalOtherPay
1999        45             2010        POLICE DEPARTMENT              229552      ORTEGA     MANUEL     2/12/2018        MANHATTAN            40782      STATIONARY ENGINEER                           ACTIVE                 508.80      per Day    2080          131779.20         1085.25  102184.53     24136.67        1
2021        816            2129        DEPT OF HEALTH/MENTAL HYGIENE  366868      THOMAS     GUAJIRA    8/14/2017        QUEENS               40257      CITY MEDICAL SPECIALIST                       ACTIVE                 99.62       per Hour   2005          220675.63         515.00   51458.78     -9809.05         1
            827            2132        DEPARTMENT OF SANITATION       168952      MC GURRAN  RAYMOND    3/22/2004        BRONX                40809      SUPERVISOR                                    ACTIVE                 108846.00   per Annum  2080          110726.63         1685.00  141839.62     15580.89        1
                                                                      139910      LOGAN      MARK       9/5/2000         BRONX                40809      SUPERVISOR                                    ACTIVE                 108846.00   per Annum  2080          110726.63         1615.02  138991.53     18294.71        1
                                                                      36130       GRAHAM     DEVON      8/21/2000        QUEENS               40809      SUPERVISOR                                    ACTIVE                 108846.00   per Annum  2080          110726.63         1808.00  153392.57     18034.19        1
                                                                                                                                                                                                                                                                                                                           ..
            462            2092        GUTTMAN COMMUNITY COLLEGE      375488      EVENBECK   SCOTT      4/17/2011        MANHATTAN            40640      PRESIDENT                                     CEASED                 228000.00   per Annum  980           122427.81         0.00     0.00          244495.20       1
            72             2017        DEPARTMENT OF CORRECTION       390816      VIKULTSEV  DMITRIY    2/19/2008        QUEENS               40440      ELECTRICIAN                                   ACTIVE                 427.35      per Day    1820          110977.00         1397.75  127746.09     23936.82        1
                                                                      324158      COX        TIA        10/11/2001       QUEENS               40864      WARDEN-ASSISTANT DEPUTY WARDEN TED < 11/1/92  ACTIVE                 128355.00   per Annum  2080          127452.46         1825.75  123102.65     16305.89        1
                                                                      310260      CLEMENTE   GARY       12/1/2008        QUEENS               40614      OILER                                         ACTIVE                 478.00      per Day    2080          124280.00         1496.25  136939.12     28268.75        1
            996            2153        NYC HOUSING AUTHORITY          332352      DALEY      GARFIELD   5/24/1994        BRONX                40812      SUPERVISOR ELECTRICIAN                        ACTIVE                 460.25      per Day    1820          119469.25         2032.50  200038.56     28316.97        1
Name: count, Length: 101, dtype: int64

In [10]:
payroll2021_df.rename(columns={'AgencyCode': 'AgencyID'}, inplace=True)

In [11]:
payroll2021_df.head()

,FiscalYear,PayrollNumber,AgencyID,AgencyName,EmployeeID,LastName,FirstName,AgencyStartDate,WorkLocationBorough,TitleCode,TitleDescription,LeaveStatusasofJune30,BaseSalary,PayBasis,RegularHours,RegularGrossPaid,OTHours,TotalOTPaid,TotalOtherPay
0,2021,996,2153,NYC HOUSING AUTHORITY,209184,MUSTACIUOLO,VITO,2/26/2018,MANHATTAN,40475,EXECUTIVE DIRECTOR,ACTIVE,258000.0,per Annum,1820,257260.30,0.00,0.00,258000.00
1,2021,996,2153,NYC HOUSING AUTHORITY,302330,RUSS,GREGORY,8/12/2019,MANHATTAN,41143,CHAIR,ACTIVE,414707.0,per Annum,1820,413518.05,0.00,0.00,500.00
2,2021,816,2129,DEPT OF HEALTH/MENTAL HYGIENE,49788,HALLAHAN,PATRICK,2/26/2018,BROOKLYN,40782,STATIONARY ENGINEER,ACTIVE,508.8,per Day,2080,132288.00,2115.25,218628.18,56616.07
3,2021,816,2129,DEPT OF HEALTH/MENTAL HYGIENE,251626,PETTIT,PATRICK,8/2/2010,MANHATTAN,40782,STATIONARY ENGINEER,ACTIVE,508.8,per Day,2080,132288.00,2152.75,218694.96,38611.82
4,2021,816,2129,DEPT OF HEALTH/MENTAL HYGIENE,364376,TELEHANY,STEPHEN,1/16/2007,QUEENS,40782,STATIONARY ENGINEER,ACTIVE,508.8,per Day,2080,132288.00,1876.25,192296.19,51160.20

In [12]:
# convert string columns to numerical values
numeric_columns = ['BaseSalary', 'RegularHours', 'RegularGrossPaid', 'OTHours', 'TotalOTPaid', 'TotalOtherPay']

In [13]:
# Convert via a forloop 
for col in numeric_columns:
    if col in payroll2020_df.columns:
        payroll2020_df[col] = pd.to_numeric(payroll2020_df[col], errors="coerce")
    if col in payroll2021_df.columns:
        payroll2021_df[col] = pd.to_numeric(payroll2021_df[col], errors="coerce")

In [14]:
# Confirm that columns have been affected
payroll2020_df.head()

,FiscalYear,PayrollNumber,AgencyID,AgencyName,EmployeeID,LastName,FirstName,AgencyStartDate,WorkLocationBorough,TitleCode,TitleDescription,LeaveStatusasofJune30,BaseSalary,PayBasis,RegularHours,RegularGrossPaid,OTHours,TotalOTPaid,TotalOtherPay
0,2020,17,2120,OFFICE OF EMERGENCY MANAGEMENT,10001,GEAGER,VERONICA,9/12/2016,BROOKLYN,40447,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,84698.21,0.0,0.0,0.00
1,2020,17,2120,OFFICE OF EMERGENCY MANAGEMENT,149612,ROTTA,JONATHAN,9/16/2013,BROOKLYN,40447,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,84698.21,0.0,0.0,0.00
2,2020,17,2120,OFFICE OF EMERGENCY MANAGEMENT,206583,WILSON II,ROBERT,4/30/2018,BROOKLYN,40447,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,84698.21,0.0,0.0,0.00
3,2020,17,2120,OFFICE OF EMERGENCY MANAGEMENT,199874,WASHINGTON,MORIAH,3/18/2019,BROOKLYN,40447,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,87900.95,0.0,0.0,-3202.74
4,2020,17,2120,OFFICE OF EMERGENCY MANAGEMENT,58036,KRAWCZYK,AMANDA,5/15/2017,BROOKLYN,40447,EMERGENCY PREPAREDNESS MANAGER,ACTIVE,86005.0,per Annum,1820.0,83976.54,0.0,0.0,0.00

In [16]:
payroll2021_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   FiscalYear             101 non-null    int64
 1   PayrollNumber          101 non-null    int64
 2   AgencyID               101 non-null    int64
 3   AgencyName             101 non-null    object
 4   EmployeeID             101 non-null    int64
 5   LastName               101 non-null    object
 6   FirstName              101 non-null    object
 7   AgencyStartDate        101 non-null    object
 8   WorkLocationBorough    101 non-null    object
 9   TitleCode              101 non-null    int64
 10  TitleDescription       101 non-null    object
 11  LeaveStatusasofJune30  101 non-null    object
 12  BaseSalary             101 non-null    float64
 13  PayBasis               101 non-null    object
 14  RegularHours           101 non-null    int64
 15  RegularGrossPaid       101 non-null    float64
 16  OTHours                101 non-null    float64
 17  TotalOTPaid            101 non-null    float64
 18  TotalOtherPay          101 non-null    float64
dtypes: float64(5), int64(6), object(8)
memory usage: 15.1+ KB

In [17]:
# change to datetime for agency start date colum
if "AgencyStartDate" in payroll2020_df.columns:
    payroll2020_df['AgencyStartDate'] = pd.to_datetime(payroll2020_df['AgencyStartDate'], errors='coerce')

if "AgencyStartDate" in payroll2021_df.columns:
    payroll2021_df['AgencyStartDate'] = pd.to_datetime(payroll2021_df['AgencyStartDate'], errors="coerce")

In [18]:
payroll2021_df.head()

,FiscalYear,PayrollNumber,AgencyID,AgencyName,EmployeeID,LastName,FirstName,AgencyStartDate,WorkLocationBorough,TitleCode,TitleDescription,LeaveStatusasofJune30,BaseSalary,PayBasis,RegularHours,RegularGrossPaid,OTHours,TotalOTPaid,TotalOtherPay
0,2021,996,2153,NYC HOUSING AUTHORITY,209184,MUSTACIUOLO,VITO,2018-02-26,MANHATTAN,40475,EXECUTIVE DIRECTOR,ACTIVE,258000.0,per Annum,1820,257260.30,0.00,0.00,258000.00
1,2021,996,2153,NYC HOUSING AUTHORITY,302330,RUSS,GREGORY,2019-08-12,MANHATTAN,41143,CHAIR,ACTIVE,414707.0,per Annum,1820,413518.05,0.00,0.00,500.00
2,2021,816,2129,DEPT OF HEALTH/MENTAL HYGIENE,49788,HALLAHAN,PATRICK,2018-02-26,BROOKLYN,40782,STATIONARY ENGINEER,ACTIVE,508.8,per Day,2080,132288.00,2115.25,218628.18,56616.07
3,2021,816,2129,DEPT OF HEALTH/MENTAL HYGIENE,251626,PETTIT,PATRICK,2010-08-02,MANHATTAN,40782,STATIONARY ENGINEER,ACTIVE,508.8,per Day,2080,132288.00,2152.75,218694.96,38611.82
4,2021,816,2129,DEPT OF HEALTH/MENTAL HYGIENE,364376,TELEHANY,STEPHEN,2007-01-16,QUEENS,40782,STATIONARY ENGINEER,ACTIVE,508.8,per Day,2080,132288.00,1876.25,192296.19,51160.20

In [23]:
# Try to check for missing employee ids
payroll_employee_ids = set(payroll2020_df['EmployeeID']).union(set(payroll2021_df['EmployeeID']))
employee_ids = set(employee_df['EmployeeID'])
missing_employees = payroll_employee_ids - employee_ids

200